# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a879e041755a233757258c164bace2584031e60139dc6785392daf31f5b154bcf89c1743d8132778ad49e9bc76732a600eb9836b468c1daf54ae7a053fcdd53

test:
  secret_key_base: a1e6ec1d498ce7ce9c2920a0a836de01ad0556e4a886a4e085b78263d01a6718750c28edc6a208868e4c2c9bad1a5b1d4b0d4f2bb1e22e866c56d574c3c5af79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# When deploying to Heroku, this gets generated from app.json at deploy time
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
