#!/usr/bin/env ruby

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  if ARGV[0].nil?
    system! 'script/update'
    system! 'bin/rails console'
  else
    # no argument provided, so just run the local console in the development
    # environment. Ensure the application is up to date first.
    system! "heroku run rails console --app #{ARGV[0]}"
  end
end
